var images = 
	[
		{
			"imgID": "img001",
			"imgDescription": "Wagen der Lokallinie der Rheinischen Bahngesellschaft",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "24",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "ca. 1900",
			"imgPath": "images/IMG_0001.jpg",
			"usedForLines": [ "l220", "l221" ]
		},
		{
			"imgID": "img002",
			"imgDescription": "Zug der Linie U70 in Hoterheide",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "25",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1996",
			"imgPath": "images/IMG_0002.jpg",
			"usedForLines": [ "l253" ]
		},
		{
			"imgID": "img003",
			"imgDescription": "Zug der Linie 10 in der Gleisschleife Reeser Platz",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "26",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1957",
			"imgPath": "images/IMG_0003.jpg",
			"usedForLines": [ "l207", "l208", "l209" ]
		},
		{
			"imgID": "img004",
			"imgDescription": "Zug der Linie 8 in der Heinrichstraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "27",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1956",
			"imgPath": "images/IMG_0004.jpg",
			"usedForLines": [ "l068" ]
		},
		{
			"imgID": "img005",
			"imgDescription": "Zug der Linie 8 in der Endstelle in Hamm",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "27",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1956",
			"imgPath": "images/IMG_0005.jpg",
			"usedForLines": [ "l068" ]
		},
		{
			"imgID": "img006",
			"imgDescription": "Zug der Linie K in Meerbusch",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "28",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1953",
			"imgPath": "images/IMG_0006.jpg",
			"usedForLines": [ "l083", "l084", "l085" ]
		},
		{
			"imgID": "img007",
			"imgDescription": "Zug der Linie 2 am Nordfriedhof",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "28",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1956",
			"imgPath": "images/IMG_0007.jpg",
			"usedForLines": [ "l323", "l324", "l325" ]
		},
		{
			"imgID": "img008",
			"imgDescription": "Zug der Linie K in Meerbusch-Hoterheide",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "30",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1966",
			"imgPath": "images/IMG_0008.jpg",
			"usedForLines": [ "l086" ]
		},
		{
			"imgID": "img009",
			"imgDescription": "Zug der Linie 10 in der Gleisschleife Vennhauser Allee",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "30",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1958",
			"imgPath": "images/IMG_0009.jpg",
			"usedForLines": [ "l208", "l209" ]
		},
		{
			"imgID": "img010",
			"imgDescription": "Züge der Linien D und K am Jan-Wellem-Platz",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "31",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1967",
			"imgPath": "images/IMG_0010.jpg",
			"usedForLines": [ "l105", "l086", "l087" ]
		},
		{
			"imgID": "img011",
			"imgDescription": "Zug der Linie 5 am Luegplatz",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "31",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1973",
			"imgPath": "images/IMG_0011.jpg",
			"usedForLines": [ "l130" ]
		},
		{
			"imgID": "img012",
			"imgDescription": "Zug der Linie K am Opernhaus auf der Heinrich-Heine-Alle",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "32",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1968",
			"imgPath": "images/IMG_0012.jpg",
			"usedForLines": [ "l086", "l087" ]
		},
		{
			"imgID": "img013",
			"imgDescription": "Zug der Linie 20 in der Fischerstraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "32",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1973",
			"imgPath": "images/IMG_0013.jpg",
			"usedForLines": []
		},
		{
			"imgID": "img014",
			"imgDescription": "Zug der Linie 709 am Obertor in Neuss",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "35",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1990",
			"imgPath": "images/IMG_0014.jpg",
			"usedForLines": [ "l176" ]
		},
		{
			"imgID": "img015",
			"imgDescription": "Zug der Linie 703 auf der Grafenberger Allee in Höhe der Irmgardstraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "35",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1982",
			"imgPath": "images/IMG_0015.jpg",
			"usedForLines": [ "l018", "l019" ]
		},
		{
			"imgID": "img016",
			"imgDescription": "Zug der Linie 711 am Jan-Wellem-Platz",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "36",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1983",
			"imgPath": "images/IMG_0016.jpg",
			"usedForLines": [ "l292", "l293" ]
		},
		{
			"imgID": "img017",
			"imgDescription": "Sonderzug zur Einweihung der neuen Triebwagengeneration an der Vennhauser Allee",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "36",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1996",
			"imgPath": "images/IMG_0017.jpg",
			"usedForLines": [ "l345" ]
		},
		{
			"imgID": "img018",
			"imgDescription": "Zug der Linie V an der Endstelle in Vohwinkel unterhalb der Wuppertaler Schwebebahn",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "38",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1996",
			"imgPath": "images/IMG_0018.jpg",
			"usedForLines": [ "l311" ]
		},
		{
			"imgID": "img019",
			"imgDescription": "Zug des Benrather Netzes, der zwischen 1906 und 1930 in Betrieb war",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "38",
			"imgCredit": "Maschinenfabrik Augsburg-Nürnberg",
			"imgYear": "",
			"imgPath": "images/IMG_0019.jpg",
			"usedForLines": [ "l277", "l278", "l279", "l307", "l308", "l309" ]
		},
		{
			"imgID": "img020",
			"imgDescription": "Zug des Mettmanner Netzes auf der Strecke zwischen Mettmann und Wülfrath",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "46",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "zwischen 1928 und 1936",
			"imgPath": "images/IMG_0020.jpg",
			"usedForLines": [ "l429" ]
		},
		{
			"imgID": "img021",
			"imgDescription": "Straßenbahn am Opernhaus in der Alleestraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "53",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "ca. 1924",
			"imgPath": "images/IMG_0021.jpg",
			"usedForLines": [ "l392", "l393", "l394", "l224", "l225", "l226", "l078", "l079", "l117", "l118", "l241", "l242" ]
		},
		{
			"imgID": "img022",
			"imgDescription": "Straßenbahn der Städtischen Straßenbahn in der Alleestraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "45",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "ca. 1900",
			"imgPath": "images/IMG_0022.jpg",
			"usedForLines": [ "l388", "l137" ]
		},
		{
			"imgID": "img023",
			"imgDescription": "Zug der Linie 17 auf der Oberkasseler Brücke",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "63",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "ca. 1926",
			"imgPath": "images/IMG_0023.jpg",
			"usedForLines": [ "l225", "l226" ]
		},
		{
			"imgID": "img024",
			"imgDescription": "Straßenbahn in der Schadowstraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "67",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "1930er Jahre",
			"imgPath": "images/IMG_0024.jpg",
			"usedForLines": [ "l395", "l396", "l397", "l398", "l399", "l028", "l010", "l298", "l299" ]
		},
		{
			"imgID": "img025",
			"imgDescription": "Zug der Linie 15 am alten Bahnhof in Oberkassel",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "68",
			"imgCredit": "Axel Schild",
			"imgYear": "",
			"imgPath": "images/IMG_0025.jpg",
			"usedForLines": [ "l301", "l302", "l303" ]
		},
		{
			"imgID": "img026",
			"imgDescription": "Zug der Linie 1 am Ratinger Tor",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "87",
			"imgCredit": "Archiv der Rheinischen Bahngesellschaft",
			"imgYear": "ca. 1956",
			"imgPath": "images/IMG_0026.jpg",
			"usedForLines": [ "l052", "l053" ]
		},
		{
			"imgID": "img027",
			"imgDescription": "Zug der Linie D am Graf-Adolf-Platz",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "91",
			"imgCredit": "Axel Schild",
			"imgYear": "1960er Jahre",
			"imgPath": "images/IMG_0027.jpg",
			"usedForLines": [ "l104", "l105" ]
		},
		{
			"imgID": "img028",
			"imgDescription": "Zug der Linie 12 in der Schadowstraße",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "140",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1980er Jahre",
			"imgPath": "images/IMG_0028.jpg",
			"usedForLines": [ "l034" ]
		},
		{
			"imgID": "img029",
			"imgDescription": "Zug fährt in der Haroldstraße in Richtung Regierungsviertel",
			"imgSource": "Die Rheinbahn",
			"imgSourceAuthor": "Axel Schild, Dieter Waltking",
			"imgSourcePage": "142",
			"imgCredit": "Dieter Waltking",
			"imgYear": "1990er Jahre",
			"imgPath": "images/IMG_0029.jpg",
			"usedForLines": [ "l259", "l177", "l376" ]
		},
		{
			"imgID": "img030",
			"imgDescription": "Gleisführung rund um die Kreuzkirche in Derendorf",
			"imgSource": "Düsseldorf. Luftbilder von gestern und heute. Eine Gegenüberstellung.",
			"imgSourceAuthor": "Clemens von Looz-Coorswarem, Manfred Czerwinski",
			"imgSourcePage": "18",
			"imgCredit": "NW Hauptstaatsarchiv Düsseldorf",
			"imgYear": "1934",
			"imgPath": "images/IMG_0030.jpg",
			"usedForLines": [ "l319", "l183", "l043", "l044", "l045" ]
		},
		{
			"imgID": "img031",
			"imgDescription": "Straßenbahnzug auf dem Burgplatz",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "21",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "ca. 1905",
			"imgPath": "images/IMG_0031.jpg",
			"usedForLines": [ "l137", "l388", "l003", "l004", "l138" ]
		},
		{
			"imgID": "img032",
			"imgDescription": "Blick in die Schadowstraße mit Straßenbahnzug",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "66",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "ca. 1930",
			"imgPath": "images/IMG_0032.jpg",
			"usedForLines": [ "l395", "l396", "l028", "l010", "l298", "l299" ]
		},
		{
			"imgID": "img033",
			"imgDescription": "Der Düsseldorfer Hauptbahnhof",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "75",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "ca. 1930",
			"imgPath": "images/IMG_0033.jpg",
			"usedForLines": [ "l383", "l317", "l318", "l319", "l170", "l063", "l120", "l285", "l330", "l331", "l436" ]
		},
		{
			"imgID": "img034",
			"imgDescription": "Straßenbahnzug am Graf-Adolf-Platz",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "74",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "1920er Jahre",
			"imgPath": "images/IMG_0034.jpg",
			"usedForLines": [ "l096", "l097", "l098", "l078", "l079", "l080", "l117", "l118", "l119", "l241", "l242", "l243", "l244", "l341", "l342", "l343", "l344", "l170", "l062", "l063", "l041", "l042", "l435", "l436"  ]
		},
		{
			"imgID": "img035",
			"imgDescription": "Straßenbahnzug auf der Grafenberger Allee",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "76",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "ca. 1900",
			"imgPath": "images/IMG_0035.jpg",
			"usedForLines": [ "l001", "l002", "l003" ]
		},
		{
			"imgID": "img036",
			"imgDescription": "Straßenbahnzüge auf dem Corneliusplatz",
			"imgSource": "Alt-Düsseldorfer Photoalbum",
			"imgSourceAuthor": "Gerda Kaltwasser",
			"imgSourcePage": "77",
			"imgCredit": "Stadtarchiv Düsseldorf",
			"imgYear": "ca. 1930",
			"imgPath": "images/IMG_0036.jpg",
			"usedForLines": [ "l028", "l298", "l435", "l436", "l042", "l043", "l201" ]
		},
		{
			"imgID": "img037",
			"imgDescription": "Zug der Linie U77 in der Station Oberbilk Bahnhof/Philipshalle",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "Rückseite",
			"imgCredit": "C. Groneck",
			"imgYear": "ca. 2007",
			"imgPath": "images/IMG_0037.jpg",
			"usedForLines": [ "l370" ]
		},
		{
			"imgID": "img038",
			"imgDescription": "Zug der Linie 715 in Eller-Mitte",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "Rückseite",
			"imgCredit": "S. Göbel",
			"imgYear": "2007",
			"imgPath": "images/IMG_0038.jpg",
			"usedForLines": [ "l345" ]
		},
		{
			"imgID": "img039",
			"imgDescription": "Zug der Linie U76 auf der Oberkasseler Brücke",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "Titelbild",
			"imgCredit": "M. Wehmeyer",
			"imgYear": "2008",
			"imgPath": "images/IMG_0039.jpg",
			"usedForLines": [ "l092" ]
		},
		{
			"imgID": "img040",
			"imgDescription": "Kleinbahn auf der Strecke zwischen Rath und Ratingen",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "23",
			"imgCredit": "Rheinbahn",
			"imgYear": "um 1900",
			"imgPath": "images/IMG_0040.jpg",
			"usedForLines": [ "l023" ]
		},
		{
			"imgID": "img041",
			"imgDescription": "Zug der Linie C in Moers",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "29",
			"imgCredit": "Rheinbahn",
			"imgYear": "um 1910",
			"imgPath": "images/IMG_0041.jpg",
			"usedForLines": [ "l238", "l239", "l240", "l241" ]
		},
		{
			"imgID": "img042",
			"imgDescription": "Zug der Linie D zwischen Düsseldorf und Duisburg",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "53",
			"imgCredit": "Rheinbahn",
			"imgYear": "ca. 1926",
			"imgPath": "images/IMG_0042.jpg",
			"usedForLines": [ "l097", "l098" ]
		},
		{
			"imgID": "img043",
			"imgDescription": "Zug der Linie D am Tag der Einweihung der neuen Wagen der Linie",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "55",
			"imgCredit": "Rheinbahn",
			"imgYear": "1926",
			"imgPath": "images/IMG_0043.jpg",
			"usedForLines": [ "l097", "l098" ]
		},
		{
			"imgID": "img045",
			"imgDescription": "Zug der Linie D am Duisburger Hauptbahnhof",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "55",
			"imgCredit": "Rheinbahn",
			"imgYear": "ca. 1926",
			"imgPath": "images/IMG_0045.jpg",
			"usedForLines": [ "l097", "l098" ]
		},
		{
			"imgID": "img046",
			"imgDescription": "Züge der Linien K und D am Graf-Adolf-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "64",
			"imgCredit": "Rheinbahn",
			"imgYear": "um 1940",
			"imgPath": "images/IMG_0046.jpg",
			"usedForLines": [ "l099", "l081" ]
		},
		{
			"imgID": "img047",
			"imgDescription": "Zug der Linie 11 in der vom Krieg gezeichneten Tonhallenstraße",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "66",
			"imgCredit": "Rheinbahn",
			"imgYear": "1951",
			"imgPath": "images/IMG_0047.jpg",
			"usedForLines": [ "l287", "l288" ]
		},
		{
			"imgID": "img048",
			"imgDescription": "Zug der Linie K in der Haltestelle Meererbusch",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "76",
			"imgCredit": "Bildsammlung P.H. Prasuhn, Archiv A. Reuther",
			"imgYear": "1951",
			"imgPath": "images/IMG_0048.jpg",
			"usedForLines": [ "l084", "l085" ]
		},
		{
			"imgID": "img049",
			"imgDescription": "Zug der Linie K kurz vor Lörick",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "76",
			"imgCredit": "D. Waltking",
			"imgYear": "1952",
			"imgPath": "images/IMG_0049.jpg",
			"usedForLines": [ "l084", "l085" ]
		},
		{
			"imgID": "img050",
			"imgDescription": "Züge der Linien D und K auf dem Jan-Wellem-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "77",
			"imgCredit": "Rheinbahn",
			"imgYear": "1962",
			"imgPath": "images/IMG_0050.jpg",
			"usedForLines": [ "l086", "l087", "l105" ]
		},
		{
			"imgID": "img051",
			"imgDescription": "Zug der Linie 79 und ein Straßenbahn-Arbeitswagen in der Station Neuer Friedhof in Duisburg",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "90",
			"imgCredit": "S. Göbel",
			"imgYear": "1980er Jahre",
			"imgPath": "images/IMG_0051.jpg",
			"usedForLines": [ "l106", "l107", "l108", "l109" ]
		},
		{
			"imgID": "img052",
			"imgDescription": "Zug der Linie K am Jan-Wellem-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "100",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "",
			"imgPath": "images/IMG_0051.jpg",
			"usedForLines": [ "l086", "l087", "l088", "l089", "l090" ]
		},
		{
			"imgID": "img053",
			"imgDescription": "Zug der Linie D in Höhe der Haltestelle Lanzallee",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "100",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "1960er Jahre",
			"imgPath": "images/IMG_0053.jpg",
			"usedForLines": [ "l105" ]
		},
		{
			"imgID": "img054",
			"imgDescription": "Züge der Linien D und 10 am Homberger Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "100",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "1960er Jahre",
			"imgPath": "images/IMG_0054.jpg",
			"usedForLines": [ "l105", "l210" ]
		},
		{
			"imgID": "img054",
			"imgDescription": "Züge der Linien D und 10 am Homberger Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "100",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "1960er Jahre",
			"imgPath": "images/IMG_0054.jpg",
			"usedForLines": [ "l105", "l210" ]
		},
		{
			"imgID": "img055",
			"imgDescription": "Zug der Linie 710 auf der Oberkasseler Brücke",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "107",
			"imgCredit": "S. Göbel",
			"imgYear": "1988",
			"imgPath": "images/IMG_0055.jpg",
			"usedForLines": [ "l234" ]
		},
		{
			"imgID": "img056",
			"imgDescription": "Zug der Linie 76 in der Bismarckstraße",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "115",
			"imgCredit": "S. Göbel",
			"imgYear": "1988",
			"imgPath": "images/IMG_0056.jpg",
			"usedForLines": [ "l090" ]
		},
		{
			"imgID": "img057",
			"imgDescription": "Züge der Linien 711 und 718 vor dem Freiligrathplatz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "119",
			"imgCredit": "S. Göbel",
			"imgYear": "1984",
			"imgPath": "images/IMG_0057.jpg",
			"usedForLines": [ "l293", "l214", "l215" ]
		},
		{
			"imgID": "img058",
			"imgDescription": "Zug der Linie 76 auf der Heinrich-Heine-Alle kurz vor Eröffnung des Innenstadttunnels",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "119",
			"imgCredit": "S. Göbel",
			"imgYear": "1988",
			"imgPath": "images/IMG_0058.jpg",
			"usedForLines": [ "l090" ]
		},
		{
			"imgID": "img059",
			"imgDescription": "Zug der Linie 77 an der Haltestelle Kaiserslauterner Straße",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "122",
			"imgCredit": "C. Groneck",
			"imgYear": "ca. 2002",
			"imgPath": "images/IMG_0059.jpg",
			"usedForLines": [ "l370" ]
		},
		{
			"imgID": "img060",
			"imgDescription": "Zug der Linie 79 in der Kaiserswerther Straße",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "135",
			"imgCredit": "S. Göbel",
			"imgYear": "1988",
			"imgPath": "images/IMG_0060.jpg",
			"usedForLines": [ "l108" ]
		},
		{
			"imgID": "img061",
			"imgDescription": "Stadtbahn- (Linie U75) und Niederflurwagen (Linie 715) in der Wendeschleife an der Vennhauser Allee",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "136",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "ca. 2008",
			"imgPath": "images/IMG_0061.jpg",
			"usedForLines": [ "l136", "l345" ]
		},
		{
			"imgID": "img062",
			"imgDescription": "Zug der Linie D in Duisburg-Huckingen",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "143",
			"imgCredit": "D. Waltking",
			"imgYear": "1958",
			"imgPath": "images/IMG_0062.jpg",
			"usedForLines": [ "l104" ]
		},
		{
			"imgID": "img063",
			"imgDescription": "Zug der Linie O in Hilden",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "143",
			"imgCredit": "D. Waltking",
			"imgYear": "1957",
			"imgPath": "images/IMG_0063.jpg",
			"usedForLines": [ "l281" ]
		},
		{
			"imgID": "img064",
			"imgDescription": "Zug der Linie D neben dem Flughafengelände",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "144",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "",
			"imgPath": "images/IMG_0064.jpg",
			"usedForLines": [ "l101", "l102", "l103", "l104", "l105" ]
		},
		{
			"imgID": "img065",
			"imgDescription": "Zug der Linie K am Jan-Wellem-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "144",
			"imgCredit": "Rheinbahn",
			"imgYear": "zwischen 1962 und 1965",
			"imgPath": "images/IMG_0065.jpg",
			"usedForLines": [ "l086" ]
		},
		{
			"imgID": "img066",
			"imgDescription": "Zug der Linie 79 zwischen Kesselsberg und Wittlaer",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "144",
			"imgCredit": "S. Göbel",
			"imgYear": "1983",
			"imgPath": "images/IMG_0066.jpg",
			"usedForLines": [ "l107", "l108" ]
		},
		{
			"imgID": "img067",
			"imgDescription": "Zug der Linie K am Jan-Wellem-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "146",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "ca. 1968",
			"imgPath": "images/IMG_0067.jpg",
			"usedForLines": [ "l086", "l087" ]
		},
		{
			"imgID": "img068",
			"imgDescription": "Zug der Linie 3 in der Schadowstraße",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "146",
			"imgCredit": "Bildsammlung P.H. Prasuhn, Archiv A. Reuther",
			"imgYear": "1959",
			"imgPath": "images/IMG_0068.jpg",
			"usedForLines": [ "l013", "l014" ]
		},
		{
			"imgID": "img069",
			"imgDescription": "Zug der Linie D am Jan-Wellem-Platz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "146",
			"imgCredit": "Volkmar Grobe",
			"imgYear": "nach 1962",
			"imgPath": "images/IMG_0069.jpg",
			"usedForLines": [ "l105" ]
		},
		{
			"imgID": "img070",
			"imgDescription": "Zug der Linie U74 in der Station Heinrich-Heine-Alle",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "148",
			"imgCredit": "S. Göbel",
			"imgYear": "2007",
			"imgPath": "images/IMG_0070.jpg",
			"usedForLines": [ "l235" ]
		},
		{
			"imgID": "img071",
			"imgDescription": "Züge der Linien U74 und U76 am Belsenplatz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "149",
			"imgCredit": "M. Wehmeyer",
			"imgYear": "2008",
			"imgPath": "images/IMG_0071.jpg",
			"usedForLines": [ "l235", "l092" ]
		},
		{
			"imgID": "img072",
			"imgDescription": "Zug der Linie U75 an der Haltestelle Tonhalle/Ehrenhof",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "149",
			"imgCredit": "M. Wehmeyer",
			"imgYear": "2008",
			"imgPath": "images/IMG_0072.jpg",
			"usedForLines": [ "l136" ]
		},
		{
			"imgID": "img073",
			"imgDescription": "Zug der Linie U78 am Freiligrathplatz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "149",
			"imgCredit": "M. Wehmeyer",
			"imgYear": "2008",
			"imgPath": "images/IMG_0073.jpg",
			"usedForLines": [ "l217" ]
		},
		{
			"imgID": "img074",
			"imgDescription": "Zug der Linie U78 in der Station Arena/Messe-Nord",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "152",
			"imgCredit": "C. Groneck",
			"imgYear": "nach 2004",
			"imgPath": "images/IMG_0074.jpg",
			"usedForLines": [ "l217", "l218", "l219" ]
		},
		{
			"imgID": "img075",
			"imgDescription": "Zug der Linie U77 an der Prinzenallee",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "154",
			"imgCredit": "C. Groneck",
			"imgYear": "ca. 2008",
			"imgPath": "images/IMG_0075.jpg",
			"usedForLines": [ "l369", "l370" ]
		},
		{
			"imgID": "img076",
			"imgDescription": "Zug der Linie U74 an der Haltestelle Provinzialplatz",
			"imgSource": "Stadtbahn Düsseldorf. Von den Anfängen des spurgeführten Verkehrs zur städteverbindenden Schnellbahn",
			"imgSourceAuthor": "Volkmar Grobe",
			"imgSourcePage": "154",
			"imgCredit": "C. Groneck",
			"imgYear": "ca. 2008",
			"imgPath": "images/IMG_0076.jpg",
			"usedForLines": [ "l235" ]
		},
		{
			"imgID": "img077",
			"imgDescription": "Pferdebahnzüge am Graf-Adolf-Platz",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "12",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "um 1895",
			"imgPath": "images/IMG_0077.jpg",
			"usedForLines": [ "l463", "l449", "l450", "l451", "l456", "l443", "l444", "l453", "l454", "l058", "l464" ]
		},
		{
			"imgID": "img078",
			"imgDescription": "Straßenbahnzug auf der Grafenberger Linie",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "12",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "um 1900",
			"imgPath": "images/IMG_0078.jpg",
			"usedForLines": [ "l461", "l459", "l001", "l002" ]
		},
		{
			"imgID": "img079",
			"imgDescription": "Straßenbahnzug auf der Ratinger Linie",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "12",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "1901",
			"imgPath": "images/IMG_0079.jpg",
			"usedForLines": [ "l023" ]
		},
		{
			"imgID": "img080",
			"imgDescription": "Straßenbahnzüge vor dem Staatsbahnhof Oberkassel",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "16",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "ca. 1902",
			"imgPath": "images/IMG_0080.jpg",
			"usedForLines": [ "l460", "l075", "l076", "l113", "l114", "l236", "l237", "l238", "l220", "l221", "l222" ]
		},
		{
			"imgID": "img081",
			"imgDescription": "Straßenbahnzüge an der Endstation an der Oberkasseler Brücke",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "28",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "ca. 1914",
			"imgPath": "images/IMG_0081.jpg",
			"usedForLines": [ "l341", "l139" ]
		},
		{
			"imgID": "img082",
			"imgDescription": "Straßenbahnzug der Linie 2 an der Endhaltestelle Friedhof",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "29",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "um 1905",
			"imgPath": "images/IMG_0082.jpg",
			"usedForLines": [ "l495", "l313", "l314" ]
		},
		{
			"imgID": "img083",
			"imgDescription": "Straßenbahnzüge der Linien 3 und 13 am Jägerhaus in Grafenberg",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "30",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "um 1908",
			"imgPath": "images/IMG_0083.jpg",
			"usedForLines": [ "l004", "l262", "l263", "l264" ]
		},
		{
			"imgID": "img084",
			"imgDescription": "Straßenbahnzug der Linie 1 auf der Moorenstraße vor den Städtischen Krankenanstalten",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "32",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "1912",
			"imgPath": "images/IMG_0084.jpg",
			"usedForLines": [ "l041" ]
		},
		{
			"imgID": "img085",
			"imgDescription": "Straßenbahnzug der Kreis Mettmanner Straßenbahn an der Endhaltestelle Auf der Hardt",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "38",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "um 1915",
			"imgPath": "images/IMG_0085.jpg",
			"usedForLines": [ "l407" ]
		},
		{
			"imgID": "img086",
			"imgDescription": "Straßenbahnzug der Linie 3 am Ende der Grafenberger Allee",
			"imgSource": "Die Geschichte der Düsseldorfer Straßenbahn. Von der Pferdetram zur Rheinbahn",
			"imgSourceAuthor": "Richard Jacobi und Dieter Zeh",
			"imgSourcePage": "40",
			"imgCredit": "Sammlung Dieter Zeh",
			"imgYear": "1912",
			"imgPath": "images/IMG_0086.jpg",
			"usedForLines": [ "l004", "l005" ]
		},
	]